### ISSUE TITLE
Read me file switch && pull requests

### ISSUE THREAD

**Issue by itsadamlove** [Sbasquil/customer-demo#1]
Your readme got moved to old readme with create react app - or maybe you did that, idk, but lets swap them back and let start using Pull Requests for this project so I can review your commits and make comments - Do you know how PRs work ?

**Comment by Sbasquil** [comment]
Yeah that was done automatically with create-react-app. I've swapped them back now. Also I'm not really sure about how the PRs work so we might have to go through how to go through that.
